### ISSUE TITLE
How to fix scroll bars and layout?

### ISSUE THREAD

**Issue by akhilm3** [Yalantis/ColorMatchTabs#10]
![thing](https://cloud.githubusercontent.com/assets/14855761/17630457/f698ce34-6084-11e6-9f2f-2429029d8c6a.gif)

How would i remove the scroll bars and lock the vertical scroll?
Also how would i put the "Reviews..etc." bar into the UINavigationBar?

**Comment by akhilm3** [comment]
Fixed it by changing nav bar from translucent to normal

**Comment by akhilm3** [comment]
Still don't know how I would remove the horizontal indicator

**Comment by serejahh** [comment]
Hi @akhilm3! It's fixed in new release, please update
