### ISSUE TITLE
Can not run the project in simulator

### ISSUE THREAD

**Issue by alex4411144** [Yalantis/ColorMatchTabs#11]
diff: /../Podfile.lock: No such file or directory
diff: /Manifest.lock: No such file or directory
error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.

**Comment by alex4411144** [comment]
error message

**Comment by serejahh** [comment]
Hi @alex4411144. Thanks for your interest to our component!
Could you specify which version of cocoapods you are using?

**Comment by gorbat-o** [comment]
Hi alex,

You just need to go in the directory where are the podfile
You do "pod install" in your terminal
and launch again your project.

Normally it's gonna be work
see ya

**Comment by serejahh** [comment]
Thanks for the answer, @gorbat-o!

@alex4411144 Did it solve your problem?

**Comment by gorbat-o** [comment]
error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.

i just saw the first line, not this one,
i can read "Run 'pod install' haha

**Comment by serejahh** [comment]
@alex4411144, please go to the `Example` directory, run `pod repo update` in the directory and then `pod install`
