### ISSUE TITLE
Objective-C Headers

### ISSUE THREAD

**Issue by electic** [Yalantis/ColorMatchTabs#14]
This is a neat project. Is there a way to use this in an objective-c project?

**Comment by serejahh** [comment]
Hi @electic! Thanks for interest to our component! 

Unfortunately, it's not possible to subclass a Swift class in Objective-C. Straight from the docs:

> You cannot subclass a Swift class in Objective-C.

But I guess you can use `MenuViewController` without subclassing and everything should work fine
