### ISSUE TITLE
Example Project Bug?

### ISSUE THREAD

**Issue by EralpB** [Yalantis/ColorMatchTabs#15]
Hello, thank you for this masterpiece!

I just downloaded made a pod install, and getting this errors on runtime.

My device is 6s iOS 9.3.3. After I click the + button it works normal but if I select something the screen becomes like this:

![image](https://cloud.githubusercontent.com/assets/2274357/17891725/e4ec02fc-693d-11e6-86f6-dbaf26026874.png)

This is happening 100% and the rest of the app is unaffected if I press + button again to close.

But if I click + button one more time then the screen is only white and the + button (meaning the icons don't float around anymore)

Is this a bug on your side?

Thank you.

```
2016-08-23 14:19:22.987 Example[3760:1600404] Unable to simultaneously satisfy constraints.
    Probably at least one of the constraints in the following list is one you don't want. 
    Try this: 
        (1) look at each constraint and try to figure out which you don't expect; 
        (2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x13d62b0f0 V:|-(687)-[UIView:0x13d5a5520]   (Names: '|':UIView:0x13d623520 )>",
    "<NSLayoutConstraint:0x13d62b240 UIView:0x13d5a5520.bottom == UIView:0x13d623520.bottom - 213.104>",
    "<NSLayoutConstraint:0x13d62cd10 'UIView-Encapsulated-Layout-Height' V:[UIView:0x13d623520(667)]>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x13d62b240 UIView:0x13d5a5520.bottom == UIView:0x13d623520.bottom - 213.104>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKit/UIView.h> may also be helpful.
```

**Comment by EralpB** [comment]
I solved it with interchanging these two lines:

topConstraint.constant += view.bounds.height
bottomConstraint.constant += view.bounds.height

but wanted to post anyway, hope it helps!

**Comment by gorbat-o** [comment]
hey, 

i don't have this problem, are you update in the last version ?
and, maybe, try to clean project and compile again !

**Comment by lmick002** [comment]
Im having this issue as well. Once you select an icon, constraints break and you get the above screen. I've update the pod as well in the project and the same issue occurs

**Comment by EralpB** [comment]
I feel like SelectItem is missing a dismissviewcontrolleranimated call.. But obviously owners can inspect better!
