### ISSUE TITLE
Cant download via cocapods

### ISSUE THREAD

**Issue by kcaglarr** [Yalantis/ColorMatchTabs#18]
Hi, I am getting this error
[!] Unable to find a specification for `ColorMatchTabs (~> 1.0)`
I tried pod 'ColorMatchTabs', '~> 1.0' 
and I tried pod `ColorMatchTabs (~> 1.0)`

**Comment by akhilm3** [comment]
Try `pod ‘ColorMatchTabs’`

**Comment by serejahh** [comment]
Hi @kcaglarr!

Did you literally add parentheses to pod file? Could you send all content of your podfile?

**Comment by nitrodamsel** [comment]
I think this is more related to CocoaPods than ColorMatchTabs. Try this http://stackoverflow.com/a/32850706

**Comment by serejahh** [comment]
@kcaglarr also run `pod repo update` in terminal. It'll update all podspec files
