### ISSUE TITLE
UIActivityIndicator over UIScrollView

### ISSUE THREAD

**Issue by jotayc** [Yalantis/ColorMatchTabs#20]
I have the UITableViewController and I'm trying add a UIActivityIndicator to waiting until it download the information to show in the table but the UIScrollView where is contained the TableViewController make that it can't be possible stay over it, then the you can scrolling vertical while the activity indicator is active. are there a way to solve this? 

Thanks.

**Comment by ZdorAnna** [comment]
Hi @jotayc. Thanks for your interest to our component!
Do you need some help? Has your problem been solved?
