### ISSUE TITLE
Perform action based on which button is tapped ?

### ISSUE THREAD

**Issue by jspenc72** [Yalantis/ColorMatchTabs#22]
Awesome project btw!

How do i inform the controller which presented the popover view and circle menu which item on the circle menu was tapped?

I know that I can override the "didSelectItemAt" method from with the popover view to get the index of the item that is tapped?
but how do am i to notify the ColorMatchTabsViewController which tab to navigate to once an item on the circle menu is tapped?

``` swift
extension ExamplePopoverViewController {
    override func circleMenu(circleMenu: CircleMenu, didSelectItemAt index: Int) {
        if(index==0){
            //Checklists

        }else if(index==1){
            //Trips


        }else if(index==2){
            //Friends

        }

        super.circleMenu(circleMenu, didSelectItemAt: index)
    }
}
```

I see that didSelectItemAt simply calls hidePopover()

``` swift
extension PopoverViewController: CircleMenuDelegate {

    public func circleMenuWillDisplayItems(circleMenu: CircleMenu) {
        moveIconsToCircle()
        showContentView()
    }

    public func circleMenuWillHideItems(circleMenu: CircleMenu) {
        moveIconsToDefaultPositions()
        hideContentMenu()
    }

    public func circleMenu(circleMenu: CircleMenu, didSelectItemAt index: Int) {
        hidePopover()
    }

}
```

And hide popover dismisses the viewController

``` swift
private extension PopoverViewController {

    @objc func hidePopover(sender: AnyObject? = nil) {
        dismissViewControllerAnimated(true, completion: nil)
    }

}
```

Any suggestions would be greatly appreciated.

Thanks in advance!

**Comment by serejahh** [comment]
Hi @jspenc72! Thanks for your interest and so detailed issues

I guess, the best solution is to add a delegate for PopoverViewController. Do you agree?

**Comment by serejahh** [comment]
Please, check https://github.com/Yalantis/ColorMatchTabs/pull/25 out

**Comment by jspenc72** [comment]
I think adding a delegate should resolve the issue.

**Comment by jspenc72** [comment]
Have you already written the code which closes this issue?
