### ISSUE TITLE
Desactivate swipe between tabs

### ISSUE THREAD

**Issue by yannbu** [Yalantis/ColorMatchTabs#23]
Hi everyone, 

On certain conditions I would like to deactivate the swipe gesture that allows to move between the tabs (to avoid to interfere with a slider I put in one of the tabs).

Do you guys know how to deactivate the swipe gesture recognizer ? Or even better, how to handle both gesture at the same time, for example by using the gesture speed (slow: move slider, fast: change tab)

Thanks !

**Comment by serejahh** [comment]
Hi @Yungbubu. Thanks for your interest!

I've created a PR. Please, check it out. Is it what you need? Scrolling is based on UIScrollView so it won't be easy enough

**Comment by yannbu** [comment]
Works like a charm!

Thanks a lot guys for your awesome work and your reactivity.

**Comment by serejahh** [comment]
Great! I'll merge the change to the `master`, so you'll be able to install it via cocoapods

**Comment by yannbu** [comment]
Perfect! Thanks again

**Comment by serejahh** [comment]
Please, update to `1.0.5`

**Comment by yannbu** [comment]
Works perferct with Cocoapods, Thanks !

**Comment by serejahh** [comment]
You are welcome 😉
