### ISSUE TITLE
I need your help

### ISSUE THREAD

**Issue by jackpaster** [Yalantis/ColorMatchTabs#29]
The problem i have is that i can't open this project in Xcode 7. Now what you would tell me is to open the project in Xcode 8 as it was intended for but i can't update my software on my computer to Xcode 8 until i upgrade the entire software on my mac to sierra. If i do that then my computer will run slow. I don't have much money and can't afford to buy more memory or a new computer. Is there a Xcode 7 version of this project. By the way love the things you guys do.

**Comment by jackpaster** [comment]
non of the storyboards open in Xcode 7

**Comment by jackpaster** [comment]
the code isn't the problem, its the xib file and main.storyboard

**Comment by serejahh** [comment]
You must have Xcode 8 to run the example project
