### ISSUE TITLE
Example Project installation with CocoaPods not possible?

### ISSUE THREAD

**Issue by inPhilly** [Yalantis/ColorMatchTabs#3]
I ran pod install for the Example project and tried to open the workspace and I get 48 errors. Tried a couple of different things and get the errors every time. Is there a problem with CocoaPods and this project?

**Comment by serejahh** [comment]
Hi @mommyme! Thanks for you interest to our component! 

I've just cloned the project, installed pods and it worked properly. Are you using Xcode 7.3? It's necessary due to swift 2.2. Also I'm using Cocoapods 1.0.1

**Comment by inPhilly** [comment]
I am using Xcode 7.3(.1). I downloaded the project and placed it in a directory. Then I navigated to the directory for Example in the Terminal and ran pod install and pod update. 48 errors.

**Comment by serejahh** [comment]
Could you provide error messages?

**Comment by akhilm3** [comment]
I also have one more thing to add, the Podfile example doesnt seem to work. I get the message 

`Unable to find a specification for `ColorMatchTabs (~> 1.0)``

**Comment by rhzs** [comment]
@mommyme In my case, I had to move project out the repo directory, then change podfile to `pod 'ColorMatchTabs', '~> 1.0'` and do `pod install` then open `.xcworkspace` and run in xcode

**Comment by serejahh** [comment]
Hi @incubus8! Have you faced the same issue with example app?

**Comment by mrcompoteee** [comment]
Hi @incubus8 and @mommyme! Could you guys also specify which version of cocoapods are you using?

**Comment by rhzs** [comment]
@mrcompoteee sorry late reply. I am using the latest cocoapods 1.0.1. 
@serejahh I didn't face the same issue with app example
