### ISSUE TITLE
TableView Statics Cells 

### ISSUE THREAD

**Issue by jaylui** [Yalantis/ColorMatchTabs#30]
### What do you want to add?

> I need to add a Static cells to TableView and loading data emptry, is for profile client & other 
> tks for help
### Your Environment
- Swift version: 2.3
- iOS version: 9.0
- Device: iphone6 plus
- Xcode version: 8

**Comment by serejahh** [comment]
Hi @jaylui

Static cells can be used only in storyboards. For now you cannot use storyboards as content view controllers. We will support it later

**Comment by rnkyr** [comment]
hey, @jaylui
basically, you should be able to achieve your requirements by instantiating your controllers and passing it to the data source
