### ISSUE TITLE
swift 3.0

### ISSUE THREAD

**Issue by jackpaster** [Yalantis/ColorMatchTabs#32]
Hello, the swift  3.0 version of colormatchtabs is not working. In Xcode 8 its saying that you need to convert the code to swift 3.0 in edit, convert. Can you please fix it

**Comment by jackpaster** [comment]
the colormatchtabs framework is causing an error and Xcode is saying that it needs to be converted to swift 3.0

**Comment by serejahh** [comment]
Duplicate of #26
