### ISSUE TITLE
Swift 3.0 crashed with project

### ISSUE THREAD

**Issue by jackpaster** [Yalantis/ColorMatchTabs#33]
I know you converted your project to swift 3.0 but the project wont build with the workspace, xcode 8 keeps asking me to convert the project to swift 3.0. I know you converted the project but can you please respond and help me

**Comment by SaifAlDilaimi** [comment]
+1

**Comment by akhilm3** [comment]
+1  
The errors given by Xcode (total 11) for @serejahh 's reference:
- Array + Safe.swift : Missing argument label 'where:' in call
- Circle Transition.swift (total 3): Method does not override any method from its superclass. Initializer for conditional binding must have Optional type., not "UIView".Cannot assign value of type "Circle Transition" to type "CAAnimationDelegate"
- ColorMatchTabsViewController.swift (total 2): ColorMatchTabsViewController.swift:153:78: Binary operator '??' cannot be applied to operands of type 'UIColor?' and '_'. And ColorMatchTabsViewController.swift:237:55: Contextual member 'white' has no associated value
- VerticalGradientView.swift (total 2) VerticalGradientView.swift:13:45: Contextual member 'white' has no associated value
  VerticalGradientView.swift:19:48: Contextual member 'black' has no associated value
- MenuView.swift MenuView.swift:48:28: Contextual member 'white' has no associated value
  MenuView.swift:64:42: Contextual member 'white' has no associated value

ColorTabs.swift Contextual member 'white' has no associated value

**Comment by qrodgers13** [comment]
+1

**Comment by serejahh** [comment]
Fixed and merged a new version to master. Please, check it our. Sorry for the long update
