### ISSUE TITLE
swift 3.0

### ISSUE THREAD

**Issue by jackpaster** [Yalantis/ColorMatchTabs#36]
You didn't fix it.

<img width="1370" alt="screen shot 2016-10-13 at 7 05 57 pm" src="https://cloud.githubusercontent.com/assets/17861785/19370200/47e360b4-9178-11e6-90b6-7a5273304180.png">

**Comment by jackpaster** [comment]
I keep telling you that its asking me to update the project to the current swift syntax. When I update I get a list full of errors

**Comment by let-aurn** [comment]
@jackpaster Try to restart xcode, then convert the code to swift 3 (error will appear), then do a Build (errors will be gone)..

**Comment by serejahh** [comment]
@jackpaster please open Example/Example.xcworkspace instead of ColorMatchTabs.xcodeproj
