### ISSUE TITLE
Switch tabs programmatically instead of tapping

### ISSUE THREAD

**Issue by yuchenglin** [Yalantis/ColorMatchTabs#39]
I would like to switch tabs programmatically. 

When the user finished each step, I can switch to next tabs subview. Also, I need to **disable some tabs' tapping event** when the user tapped tabs which they should not arrive. How can I do that in this project?

Thanks for this gorgeous project!

**Comment by Juice805** [comment]
To programmatically switch tabs use the `selectItem(at: Index)` function in the `ColorMatchTabsViewController` class
