### ISSUE TITLE
Tabs are overlapped by navigation bar

### ISSUE THREAD

**Issue by Jack0805** [Yalantis/ColorMatchTabs#45]
Hi, the tab bar is covered by the navigation bar, is there any solution for this? Thanks!
<img width="370" alt="overlap" src="https://cloud.githubusercontent.com/assets/18099137/22236354/1adb999c-e259-11e6-9f84-27eb1c684b13.png">

**Comment by ValentinKuznetsov** [comment]
same

**Comment by Juice805** [comment]
In the provided example the navigation bar is opaque which by default View Controllers do not extend under. To fix yours select the navigation controller's navigation bar and uncheck "Translucent" in the attribute inspector
