### ISSUE TITLE
Put tab bar on bottom

### ISSUE THREAD

**Issue by Jack0805** [Yalantis/ColorMatchTabs#46]
is there any way to arrange the tab bar on bottom instead of top?

**Comment by serejahh** [comment]
Hi @Jack0805 for now you cannot do it

**Comment by Jack0805** [comment]
I have done it, thanks anyway!
<img width="376" alt="untitled" src="https://cloud.githubusercontent.com/assets/18099137/23554542/a6a9a7fa-0079-11e7-80ba-e735fed22bb5.png">

**Comment by serejahh** [comment]
We'd like if you create a pull request with an example how to do it :)

**Comment by Jack0805** [comment]
private extension MenuView {
    
    func layoutNavigationBar() {
        navigationBar.translatesAutoresizingMaskIntoConstraints = false
        navigationBar.leadingAnchor.constraint(equalTo: leadingAnchor).isActive = true
        //navigationBar.topAnchor.constraint(equalTo: topAnchor).isActive = true
        navigationBar.bottomAnchor.constraint(equalTo: bottomAnchor, constant: 6).isActive = true
        //navigationBar.bottomAnchor.constraint(equalTo: topAnchor, constant: 4).isActive = true
        navigationBar.trailingAnchor.constraint(equalTo: trailingAnchor).isActive = true
        navigationBar.heightAnchor.constraint(equalToConstant: 50).isActive = true
    }
    
    func layoutTabs() {
        tabs.translatesAutoresizingMaskIntoConstraints = false
        tabs.leadingAnchor.constraint(equalTo: navigationBar.leadingAnchor).isActive = true
        tabs.topAnchor.constraint(equalTo: navigationBar.topAnchor).isActive = true
        tabs.trailingAnchor.constraint(equalTo: navigationBar.trailingAnchor).isActive = true
        tabs.heightAnchor.constraint(equalToConstant: 44).isActive = true
    }
    
    func layoutScrollMenu() {
        scrollMenu.translatesAutoresizingMaskIntoConstraints = false
        scrollMenu.leadingAnchor.constraint(equalTo: leadingAnchor).isActive = true
        //scrollMenu.topAnchor.constraint(equalTo: navigationBar.bottomAnchor).isActive = true
        scrollMenu.topAnchor.constraint(equalTo: topAnchor).isActive = true
        scrollMenu.trailingAnchor.constraint(equalTo: trailingAnchor).isActive = true
        //scrollMenu.bottomAnchor.constraint(equalTo: bottomAnchor).isActive = true
        scrollMenu.bottomAnchor.constraint(equalTo: navigationBar.topAnchor).isActive = true
    }
    
    func layoutShadowView() {
        shadowView.translatesAutoresizingMaskIntoConstraints = false
        shadowView.leadingAnchor.constraint(equalTo: leadingAnchor).isActive = true
        shadowView.trailingAnchor.constraint(equalTo: trailingAnchor).isActive = true
        shadowView.bottomAnchor.constraint(equalTo: bottomAnchor).isActive = true
        shadowView.heightAnchor.constraint(equalToConstant: 80).isActive = true
    }
    
    func layoutCircleMenu() {
        circleMenuButton.translatesAutoresizingMaskIntoConstraints = false
        circleMenuButton.bottomAnchor.constraint(equalTo: bottomAnchor, constant: PlusButtonButtonOffset).isActive = true
        circleMenuButton.centerXAnchor.constraint(equalTo: centerXAnchor).isActive = true
    }
    
}

**Comment by cjbhojani** [comment]
Hello there,
This is not working my project can you help me for this ??

Thank you :)
