### ISSUE TITLE
Segues from ColorMatchTabsViewController produces Exception

### ISSUE THREAD

**Issue by Juice805** [Yalantis/ColorMatchTabs#47]
###  What did you do?

called `self.performSegue(withIdentifier: "addItem", sender: self)`  in the protocol method `func popoverViewController(_ popoverViewController: PopoverViewController, didSelectItemAt index: Int)` PopoverViewControllerDelegate function.

Or initiating a segue by tapping a button on the navigation bar of a `ColorMatchTabsViewController`

### What did you expect to happen?

Segue to another view controller

### What happened instead?

Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSArrayM insertObject:atIndex:]: object cannot be nil'`

### Your Environment

- Version of the component: 2.0.1
- Swift version: 3
- iOS version: 10
- Device: All
- Xcode version: 8.2.1

### Project that demonstrates the bug

Sample project reproduces the bug by adding either a button to the nav bar with a segue, or initiating one

**Comment by rafaelnicolett** [comment]
Same problem here.

**Comment by minseks** [comment]
Same problem too.
I spend a few hours to locate this bug.
It was caused by the overrided method
 `open override func loadView() {
view = MenuView()
    }` in `ColorMatchTabsViewController`.

You should add **`super.loadView()`** before add your own code like this:
`open override func loadView() {
        super.loadView()
        view = MenuView()
    }`
 After that, everything is ok!
