### ISSUE TITLE
fatal error: Index out of range

### ISSUE THREAD

**Issue by akhilm3** [Yalantis/ColorMatchTabs#5]
I have followed the example, and running the code results in the above error in the 

```
func moveHighlighterView(toItemAt toIndex: Int) {
        guard let countItems = dataSource?.numberOfItems(inTabSwitcher: self) where countItems > toIndex else {
            return
        }

        let toLabel = labels[toIndex]
        let toIcon = buttons[toIndex]

        // offset for first item
        let point = convertPoint(toIcon.frame.origin, toView: self)
        let offsetForFirstItem: CGFloat = toIndex == 0 ? -HighlighterViewOffScreenOffset : 0
        highlighterView.frame.origin.x = point.x + offsetForFirstItem

        // offset for last item
        let offsetForLastItem: CGFloat = toIndex == countItems - 1 ? HighlighterViewOffScreenOffset : 0
        highlighterView.frame.size.width = toLabel.bounds.width + (toLabel.frame.origin.x - toIcon.frame.origin.x) + 10 - offsetForFirstItem + offsetForLastItem

        highlighterView.backgroundColor = dataSource!.tabSwitcher(self, tintColorAt: toIndex)
    } 
```

section of the ColorMatchTabs Source Code

**Comment by serejahh** [comment]
Hi @akhilm3! Thanks for reporting the issue

Have you faced the issue in our example or in your own?

**Comment by akhilm3** [comment]
In my own code, I basically followed the example but put everything into one file and changing a few lines to get them to work.

**Comment by serejahh** [comment]
Could you describe what you've changed? It'd be great if you can provide the project with the crash

**Comment by mooseDev** [comment]
The Bug is 100% reproducible.
1. Support landscape and portrait mode (example is only portrait)
2. Run the app
3. Rotate to landscape and select e.g. item 3
4. Rotate back to portrait mode
5. Crash in:

`func tabsViewController(controller: ColorMatchTabsViewController, tintColorAt index: Int) -> UIColor {
        return TabItemsProvider.items[index].tintColor
    }
`

**Comment by serejahh** [comment]
@mooseDev, thanks for the report. I'll investigate the issue

**Comment by serejahh** [comment]
@mooseDev currently we don't support landscape orientation. If you wanna fix it, please, create a PR

**Comment by akhilm3** [comment]
Still getting this error in portrait mode and ive copied almost everything except i changed the viewcontrollers to my own.

**Comment by akhilm3** [comment]
Never mind i fixed it by adding `reloadData()` Sorry for the hassle
