### ISSUE TITLE
Move tabbar to bottom

### ISSUE THREAD

**Issue by tuononh** [Yalantis/ColorMatchTabs#54]
This should labeled as a question. Can I move the tabbar to bottom?

**Comment by srj0x0** [comment]
@ptaking Hi! At now, you can't. But I hope you will able to do it in the next version.

**Comment by thakurkrishna1991** [comment]
i have changed few line of code to move tabbar to bottom 

`private extension MenuView {
    
    func layoutNavigationBar() {
        navigationBar.translatesAutoresizingMaskIntoConstraints = false
        navigationBar.leadingAnchor.constraint(equalTo: leadingAnchor).isActive = true
        navigationBar.bottomAnchor.constraint(equalTo: bottomAnchor).isActive = true
        navigationBar.trailingAnchor.constraint(equalTo: trailingAnchor).isActive = true
        navigationBar.heightAnchor.constraint(equalToConstant: 60).isActive = true
    }
    
    func layoutTabs() {
        tabs.translatesAutoresizingMaskIntoConstraints = false
        tabs.leadingAnchor.constraint(equalTo: navigationBar.leadingAnchor).isActive = true
        tabs.topAnchor.constraint(equalTo: navigationBar.topAnchor, constant: 5).isActive = true
        tabs.trailingAnchor.constraint(equalTo: navigationBar.trailingAnchor).isActive = true
        tabs.heightAnchor.constraint(equalToConstant: 50).isActive = true
    }
    
    func layoutScrollMenu() {
        scrollMenu.translatesAutoresizingMaskIntoConstraints = false
        scrollMenu.leadingAnchor.constraint(equalTo: leadingAnchor).isActive = true
        scrollMenu.topAnchor.constraint(equalTo: topAnchor).isActive = true
        scrollMenu.trailingAnchor.constraint(equalTo: trailingAnchor).isActive = true
        scrollMenu.bottomAnchor.constraint(equalTo: bottomAnchor).isActive = true
    }
    
    func layoutShadowView() {
        shadowView.translatesAutoresizingMaskIntoConstraints = false
        shadowView.leadingAnchor.constraint(equalTo: leadingAnchor).isActive = true
        shadowView.trailingAnchor.constraint(equalTo: trailingAnchor).isActive = true
        shadowView.bottomAnchor.constraint(equalTo: bottomAnchor).isActive = true
        shadowView.heightAnchor.constraint(equalToConstant: 80).isActive = true
    }
    
    func layoutCircleMenu() {
        circleMenuButton.translatesAutoresizingMaskIntoConstraints = false
        circleMenuButton.bottomAnchor.constraint(equalTo: bottomAnchor, constant: PlusButtonButtonOffset).isActive = true
        circleMenuButton.centerXAnchor.constraint(equalTo: centerXAnchor).isActive = true
    }
    
}
`

**Comment by rnkyr** [comment]
so, you can achieve your goal with the code above and some basic inheritance. closing the issue

**Comment by cjbhojani** [comment]
Hello there, 
This is not working in my Project if you have other solution than please suggest me.

Thank you :)
