### ISSUE TITLE
Enable scroll in tabs

### ISSUE THREAD

**Issue by Abacaxi-Nelson** [Yalantis/ColorMatchTabs#56]
Hi all,

Have you tried to add ˜20 tabs, only 6 tabs are displayed..
Do you know how to enable scroll ?

Thanks,

**Comment by srj0x0** [comment]
@tugal Hello! Unfortunately, it can't be done for now. I hope, you will be able to do it in the next version.

**Comment by rnkyr** [comment]
closing the issue since it is possible in current implementation
