### ISSUE TITLE
Make popover button optional

### ISSUE THREAD

**Issue by mooseDev** [Yalantis/ColorMatchTabs#6]
Currently the button is always shown. Even if no viewcontroller was set as a popovercontroller. Would be fine to deactivate the button if needed...

**Comment by serejahh** [comment]
Hi @mooseDev. Thanks for interest to our component! 
Sure, I'll add it on the week

**Comment by mooseDev** [comment]
@serejahh  thanks :)

**Comment by serejahh** [comment]
Hi @mooseDev! Now the button is shown only if a popover is set

**Comment by mooseDev** [comment]
@serejahh  thanks :)

**Comment by akhilm3** [comment]
How would we set it?

**Comment by serejahh** [comment]
Hi @akhilm3!
Take a look at:
https://github.com/Yalantis/ColorMatchTabs/blob/8e29b006164d690d8fc4d98f1e950266947aa9a8/Example/Example/Classes/ViewControllers/ExampleViewContoller.swift#L18

**Comment by akhilm3** [comment]
Thanks
