### ISSUE TITLE
How To?

### ISSUE THREAD

**Issue by xhiza** [Yalantis/ColorMatchTabs#61]
Hi, 
I would really be thankful if someone could help me figured it out.
Trying to implement in my project, but I fail.
Really appreciate if someone have a simple tutorial.

Thanks

**Comment by rnkyr** [comment]
Hello, @xhiza!
Please, refer to the Example project and "How to use" section of a readme.
Github's issues is a tool for a bug reporting, not to ask questions. Feel free to ask it on StackOverflow
