### ISSUE TITLE
@IBInspectable Error

### ISSUE THREAD

**Issue by ghost** [Yalantis/ColorMatchTabs#62]
I keep getting this Error:
> Property cannot be marked @IBInspectable because its type cannot be represented in Objective-C

on the following line of code in _ColorMatchTabsViewControllerDataSource_:
> @IBInspectable open weak var dataSource: ColorMatchTabsViewControllerDataSource? {
}

<img width="1308" alt="bildschirmfoto 2018-01-25 um 22 37 39" src="https://user-images.githubusercontent.com/7954676/35413653-6f87e44a-0220-11e8-9b63-b34b812eebc8.png">

**Comment by ghost** [comment]
<img width="1021" alt="bildschirmfoto 2018-01-26 um 00 08 28" src="https://user-images.githubusercontent.com/7954676/35417310-2aa0c22c-022d-11e8-857d-c4e6a62ce023.png">

**Comment by rnkyr** [comment]
Hi, @ro66s!
This happens because you can't mark dataSource as `IBInspectable`, since it's not view

**Comment by dieptx** [comment]
@rnkyr How to fix it when i installed this pod ?

**Comment by rnkyr** [comment]
Hi, @dieptran00888 
Thanks for pointing out this issue one more time. I've fixed it in `feature/swift-4`
Cocoapods trunk will be updated in a few days. Meanwhile, you can check the fixe directly from `master` branch
