### ISSUE TITLE
Issue with visible content / and contentSizes after orientation change

### ISSUE THREAD

**Issue by mooseDev** [Yalantis/ColorMatchTabs#7]
**PreCondition:**
- Example project
- Enable landscape support

**Action:**
- Switch to 'Places' in portrait mode
- Rotate device to landscape

**Result:**
- Half content view shows "Places" content and the other half (left side) showing content from first tab 'Products'

**Expected:**
- correct content size after orientation change

**Note:**
- ScrollMenu.swift L.123ff -> layoutContent()
- I'll have a look at it tomorrow

**Comment by mooseDev** [comment]
Quick workaround:

ScrollMenu.swift 

`    override public func layoutSubviews() {
        super.layoutSubviews()

```
    layoutContent()
    let contentOffsetX = bounds.width * CGFloat(currentPage)
    setContentOffset(CGPoint(x: contentOffsetX, y: contentOffset.y), animated: false)
}`
```

We need to store 'currentPage' - maybe good idea to make it public.

@serejahh: Feedback? :)

**Comment by mooseDev** [comment]
@serejahh: Oh didn't see your fix. Thought you just closed the issue. 

Your latest fix caused wrong index after rotation.
1. Portrait - Index 2 selected
2. Rotate
3. Landscape - Index 2 still selected
4. Rotate
5. Portrait - Index 3 selected !!!

Haven't seen the issue with my workaround though... Going to test a lil bit more

**Comment by serejahh** [comment]
Please check if your fix works better. Then I'll merge it

**Comment by serejahh** [comment]
It seems it works, but when you tap on a tabbar item, a page doesn't change and you can't swipe

**Comment by mooseDev** [comment]
yes you are correct - swipe is broken with my workaround but correct index is shown :(

**Comment by mooseDev** [comment]
> ```
> public var indexOfVisibleItem: Int {
>     if bounds.width > 0 {
>         return Int(round(contentOffset.x / bounds.width))
>     }
>     return 0
> }
> ```

is returning wrong index after 2nd orientation change. So 'previousIndex' will be messed up.

Maybe related to "Out Of Range" bug ?

**Comment by serejahh** [comment]
Seems to be true. When a device is just been rotated from landscape to portrait, `bounds` is for portrait, but `contentSize` and `contentOffset` are for landscape

**Comment by sadanand-lowanshi** [comment]
Still getting issue in landscape mode
